version: '3.3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: 'delivery'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    volumes:
      - my-db:/var/lib/postgresql/data
  dbadmin:
    image: dpage/pgadmin4
    links:
      - db
    ports:
      - '8080:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@example.com
      - PGADMIN_DEFAULT_PASSWORD=password
  redis:
    image: 'redis:latest'
    container_name: 'redis'
    ports:
      - '6379:6379'
volumes:
  my-db:
